// Generated by CoffeeScript 1.7.1
(function() {
  var o;

  o = require('observable');

  o.compute = function(observables, compute) {
    var byes, cur, init, v;
    cur = observables.map(function(e) {
      return e();
    });
    init = true;
    v = o();
    byes = observables.map(function(f, i) {
      return f(function(val) {
        cur[i] = val;
        if (init) {
          return;
        }
        return v(compute.apply(null, cur));
      });
    });
    v(compute.apply(null, cur));
    init = false;
    v.$destroy = function() {
      return byes.forEach(function(f) {
        return f();
      });
    };
    return v;
  };

  module.exports = o;

}).call(this);
